import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { SmoothScroll } from "@/components/smooth-scroll";
import { ProjectTransitionProvider } from "@/components/project-transition";

const exo2 = Exo_2({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-exo-2",
});

export const metadata: Metadata = {
  title: "Halk Soluctions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo2.variable} ${exo2.className} antialiased`}
      >
        <SmoothScroll>
          <ProjectTransitionProvider>
            <Header />
            {children}
          </ProjectTransitionProvider>
        </SmoothScroll>
      </body>
    </html>
  );
}
